// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Policy.API.Infrastructure.Data.Entities
{
    public partial class PolicyHolder
    {
        public PolicyHolder()
        {
            Offers = new HashSet<Offer>();
            PolicyVersions = new HashSet<PolicyVersion>();
        }

        public int PolicyHolderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Pesel { get; set; }
        public int AddressId { get; set; }

        public virtual Address Address { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<PolicyVersion> PolicyVersions { get; set; }
    }
}