// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Policy.API.Infrastructure.Data.Entities
{
    public partial class PolicyValidityPeriod
    {
        public PolicyValidityPeriod()
        {
            Offers = new HashSet<Offer>();
            PolicyCovers = new HashSet<PolicyCover>();
            PolicyVersionCoverPeriodPolicyValidityPeriods = new HashSet<PolicyVersion>();
            PolicyVersionVersionValidityPeriodPolicyValidityPeriods = new HashSet<PolicyVersion>();
        }

        public int PolicyValidityPeriodId { get; set; }
        public DateTime PolicyFrom { get; set; }
        public DateTime PolicyTo { get; set; }

        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<PolicyCover> PolicyCovers { get; set; }
        public virtual ICollection<PolicyVersion> PolicyVersionCoverPeriodPolicyValidityPeriods { get; set; }
        public virtual ICollection<PolicyVersion> PolicyVersionVersionValidityPeriodPolicyValidityPeriods { get; set; }
    }
}