// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Product.API.Infrastructure.Data.Entities
{
    public partial class Choice
    {
        public int ChoiceId { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public int QuestionId { get; set; }

        public virtual Question Question { get; set; }
    }
}