// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Product.API.Infrastructure.Data.Entities
{
    public partial class Cover
    {
        public int CoverId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Optional { get; set; }
        public decimal? SumInsured { get; set; }
        public int ProductId { get; set; }

        public virtual Product Product { get; set; }
    }
}