// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Product.API.Infrastructure.Data.Entities
{
    public partial class Product
    {
        public Product()
        {
            Covers = new HashSet<Cover>();
            Questions = new HashSet<Question>();
        }

        public int ProductId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public int MaxNumberOfInsured { get; set; }
        public int ProductStatusId { get; set; }

        public virtual ProductStatus ProductStatus { get; set; }
        public virtual ICollection<Cover> Covers { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}