// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Product.API.Infrastructure.Data.Entities
{
    public partial class Question
    {
        public Question()
        {
            Choices = new HashSet<Choice>();
        }

        public int QuestionId { get; set; }
        public string Code { get; set; }
        public int Index { get; set; }
        public string Text { get; set; }
        public int ProductId { get; set; }
        public int QuestionTypeId { get; set; }

        public virtual Product Product { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual ICollection<Choice> Choices { get; set; }
    }
}